version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - myapp-net   # 👈 custom network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - myapp-net   # 👈 custom network

volumes:
  db_data:

networks:
  myapp-net:   # 👈 custom network definition
